accounts:
  - name: paranaue
    coins: ["20000000000cto"]
  - name: bob
    coins: ["100000000cto"]
validator:
  name: paranaue
  staked: "100000000cto"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["20cto"]

genesis:
  app_state:
    staking:
      params:
        bond_denom: "cto"

    crisis:
      constant_fee:
        amount: "1000"
        denom: "cto"

    gov:
      deposit_params:
        min_deposit:
          - amount: "1000000"
            denom: "cto"
    mint:
      params:
        mint_denom: "cto"